"""Deterministic epistemic uncertainty analysis over committed PEF state.

Uncertainty is a property of the committed world model, not of text.
This module interrogates PEF state directly — it does not call any LLM.

Detectable uncertainty kinds from current PEF (see CORE_UNCERTAINTY_KINDS):
  conflicting_models   — same subject/predicate with incompatible committed values
  unconfirmed_status   — entities committed as unresolved (resolved=False)
  blocked_access       — retrieval_unresolved items (evidence that could not be admitted)
  missing_observation  — expected observation absent, inconclusive, or pending
                         (requires claim_status="pending" from the extraction layer)
  predictive_uncertainty — outcome depends on an event that has not yet occurred
                           (requires claim_status="pending" on a future-facing claim)
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, Any

from aurora_lens.trust.trust_contract import parse_trust_contract

if TYPE_CHECKING:
    from aurora_lens.pef.state import PEFState
    from aurora_lens.trust.trust_registry import TrustRegistry

# ── Uncertainty kind taxonomy ──────────────────────────────────────────
#
# Three distinct sets; keep them separate.
#
# CORE_UNCERTAINTY_KINDS             — generated by pef_uncertainty_analysis() from committed PEF state
# EXTERNAL_ESTABLISHMENT_FAILURE_KINDS — externally declared; never generated by this module;
#                                        no generators yet (Phase 2: vocabulary and recognition only)
# RETRIEVAL_UNRESOLVED_KINDS         — admission-layer artefacts on PEFState.retrieval_unresolved;
#                                      structurally separate, defined in rag_pef_admission.py
#
# VALID_OPEN_EPISTEMIC_KINDS         — union; the full set accepted in
#                                      evidence_state.open_epistemic_uncertainties payloads;
#                                      gate remains permissive and does not reject unknown strings

CORE_UNCERTAINTY_KINDS: frozenset[str] = frozenset({
    "conflicting_models",      # two or more committed sources disagree on the same fact
    "missing_observation",     # expected observation absent, inconclusive, or pending
    "blocked_access",          # evidence cannot be reached or admitted
    "unconfirmed_status",      # current state of a critical entity is unknown or unresolved
    "predictive_uncertainty",  # outcome depends on an event that has not yet occurred
})

EXTERNAL_ESTABLISHMENT_FAILURE_KINDS: frozenset[str] = frozenset({
    "identity_or_referent_unresolved",  # claim cannot attach to a unique entity or referent
    "stale_evidence",                   # evidence exists but is no longer current for this consequence
    "inferential_gap",                  # committed evidence does not support the conclusion
    "threshold_not_met",                # evidence is present but below the required evidential threshold
    "source_untrusted",                 # source fails provenance, authority, or admissibility requirements
    "scope_mismatch",                   # evidence is from a different entity/population/domain/jurisdiction
})

VALID_OPEN_EPISTEMIC_KINDS: frozenset[str] = (
    CORE_UNCERTAINTY_KINDS | EXTERNAL_ESTABLISHMENT_FAILURE_KINDS
)

# Backward-compat alias — prefer CORE_UNCERTAINTY_KINDS in new code.
UNCERTAINTY_KINDS = CORE_UNCERTAINTY_KINDS

# Phase 2+3 implementation posture per establishment-failure kind.
# - deterministic_generated: produced from committed state without LLM classification.
# - external_declared_only: caller may declare; no deterministic generator yet.
PHASE2_ESTABLISHMENT_FAILURE_IMPLEMENTATION: dict[str, str] = {
    "identity_or_referent_unresolved": "deterministic_generated",
    "stale_evidence": "deterministic_generated",
    "source_untrusted": "external_declared_only",
    "scope_mismatch": "deterministic_generated",
    "threshold_not_met": "deterministic_generated",
    "inferential_gap": "deterministic_generated",
}

# Optional supplementary metadata contract for external declaration paths.
# These are additive caller-side fields only; gate semantics stay unchanged.
PHASE2_EXTERNAL_METADATA_OPTIONAL_FIELDS: dict[str, frozenset[str]] = {
    "stale_evidence": frozenset({
        "decay_mode",
        "timestamp_source",
        "observed_at",
        "asserted_at",
        "ingested_at",
        "as_of",
        "assessed_at",
        "decision_time",
        "valid_until",
        "freshness_window",
        "evidence_ref",
        "claim_key",
        "supersession_rule",
        "committed_at",
        "supersedes_ref",
        "consequence_grade",
        "policy_ref",
    }),
    "source_untrusted": frozenset({
        "source_id",
        "source_class",
        "trust_basis",
        "trust_registry_ref",
        "authority_map_ref",
        "trust_decision",
        "policy_ref",
        "trust_evaluation_required",
        "task_domain",
        "consequence_grade",
    }),
    "scope_mismatch": frozenset({
        "required_scope",
        "supported_scope",
        "evidence_scope",  # deprecated alias for supported_scope
        "scope_dimensions",
        "comparison_mode",
        "failed_dimensions",
        "policy_ref",
    }),
    "threshold_not_met": frozenset({
        "required_strength",
        "observed_strength",
        "consequence_grade",
        "threshold_ref",
        "comparison_mode",
        "policy_ref",
    }),
    "inferential_gap": frozenset({
        "premises",
        "conclusion",
        "bridge_ref",
        "bridge_status",
        "bridge_mode",
        "missing_support",  # deprecated alias for premises in external declarations
        "policy_ref",
    }),
}

_GENERATED_IDENTITY_REFERENT_UNRESOLVED_ID_PREFIX = (
    "generated_identity_or_referent_unresolved:"
)
_GENERATED_STALE_EVIDENCE_ID_PREFIX = "generated_stale_evidence:"
_GENERATED_SCOPE_MISMATCH_ID_PREFIX = "generated_scope_mismatch:"
_GENERATED_THRESHOLD_NOT_MET_ID_PREFIX = "generated_threshold_not_met:"
_GENERATED_INFERENTIAL_GAP_ID_PREFIX = "generated_inferential_gap:"
_GENERATED_SOURCE_UNTRUSTED_ID_PREFIX = "generated_source_untrusted:"

# Explicit scope-comparison contract for scope_mismatch (four parts).
SCOPE_DIMENSION_ALLOWED: frozenset[str] = frozenset({
    "subject",
    "action_type",
    "domain",
    "jurisdiction",
    "timeframe",
    "consequence_grade",
    "authority_level",
})
SCOPE_COMPARISON_MODES: frozenset[str] = frozenset({
    "exact",
    "subset_allowed",
    "superset_allowed",
})

# Explicit threshold-comparison contract for threshold_not_met (four parts + mode).
THRESHOLD_CONSEQUENCE_GRADES: frozenset[str] = frozenset({
    "minimal",
    "low",
    "moderate",
    "high",
    "critical",
})
THRESHOLD_COMPARISON_MODES: frozenset[str] = frozenset({
    "gte",
    "gt",
    "exact",
})
THRESHOLD_COMPARISON_MODE_DEFAULT = "gte"

# Explicit bridge contract for inferential_gap (four parts + bridge_mode).
INFERENTIAL_BRIDGE_STATUSES: frozenset[str] = frozenset({
    "valid",
    "missing",
    "contradicted",
    "expired",
    "out_of_scope",
})
INFERENTIAL_BRIDGE_MODES: frozenset[str] = frozenset({
    "requires_declared_bridge",
})
INFERENTIAL_BRIDGE_MODE_DEFAULT = "requires_declared_bridge"


def normalize_consequence_grade(raw: Any) -> str | None:
    grade = str(raw or "").strip().lower()
    if grade in THRESHOLD_CONSEQUENCE_GRADES:
        return grade
    return None


def normalize_threshold_comparison_mode(raw: Any) -> str | None:
    mode = str(raw or "").strip().lower()
    if mode in THRESHOLD_COMPARISON_MODES:
        return mode
    return None


def normalize_strength_value(raw: Any) -> float | None:
    if isinstance(raw, (int, float)) and not isinstance(raw, bool):
        return float(raw)
    return None


def threshold_comparison_fails(
    observed_strength: float,
    required_strength: float,
    comparison_mode: str,
) -> bool:
    """Return True when declared strengths fail the comparison under comparison_mode."""
    mode = normalize_threshold_comparison_mode(comparison_mode)
    if mode is None:
        return False
    if mode == "gte":
        return observed_strength < required_strength
    if mode == "gt":
        return observed_strength <= required_strength
    return observed_strength != required_strength


def parse_premises(raw: Any) -> list[str] | None:
    """Parse declared premise list; reject empty or informal shapes."""
    if not isinstance(raw, (list, tuple)):
        return None
    premises: list[str] = []
    for item in raw:
        s = str(item).strip()
        if s and s not in premises:
            premises.append(s)
    return premises if premises else None


def normalize_bridge_status(raw: Any) -> str | None:
    status = str(raw or "").strip().lower()
    if status in INFERENTIAL_BRIDGE_STATUSES:
        return status
    return None


def normalize_inferential_bridge_mode(raw: Any) -> str | None:
    mode = str(raw or "").strip().lower()
    if mode in INFERENTIAL_BRIDGE_MODES:
        return mode
    return None


def bridge_status_indicates_gap(bridge_status: str) -> bool:
    """Return True when declared bridge_status is not valid under v1 contract."""
    status = normalize_bridge_status(bridge_status)
    if status is None:
        return False
    return status != "valid"


def normalize_scope_value_dict(raw: Any) -> dict[str, str] | None:
    """Normalize a scope dict to allowed dimensions with non-empty string values."""
    if not isinstance(raw, dict):
        return None
    out: dict[str, str] = {}
    for key, val in raw.items():
        dim = str(key).strip()
        if dim not in SCOPE_DIMENSION_ALLOWED:
            continue
        s = str(val).strip()
        if s:
            out[dim] = s
    return out if out else None


def parse_scope_dimensions(raw: Any) -> list[str] | None:
    """Parse declared comparison axes; reject unknown or empty lists."""
    if not isinstance(raw, (list, tuple)):
        return None
    dims: list[str] = []
    for item in raw:
        dim = str(item).strip()
        if dim not in SCOPE_DIMENSION_ALLOWED:
            return None
        if dim not in dims:
            dims.append(dim)
    return dims if dims else None


def compare_scope_failure_dimensions(
    required: dict[str, str],
    supported: dict[str, str],
    dimensions: list[str],
    comparison_mode: str,
) -> list[str]:
    """Return dimensions that fail deterministic comparison under comparison_mode.

    v1 applies per-dimension token equality for all three modes. Hierarchical
    subset/superset semantics require explicit partial orders on dimension
    values and are reserved for a later contract extension.
    """
    mode = str(comparison_mode or "").strip().lower()
    if mode not in SCOPE_COMPARISON_MODES:
        return []
    failed: list[str] = []
    for dim in dimensions:
        if required.get(dim) != supported.get(dim):
            failed.append(dim)
    return failed


# ── Merge utility ──────────────────────────────────────────────────────

def _is_generated_identity_referent_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "identity_or_referent_unresolved":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_IDENTITY_REFERENT_UNRESOLVED_ID_PREFIX)


def _is_generated_stale_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "stale_evidence":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_STALE_EVIDENCE_ID_PREFIX)


def _is_generated_scope_mismatch_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "scope_mismatch":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_SCOPE_MISMATCH_ID_PREFIX)


def _is_generated_threshold_not_met_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "threshold_not_met":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_THRESHOLD_NOT_MET_ID_PREFIX)


def _is_generated_inferential_gap_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "inferential_gap":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_INFERENTIAL_GAP_ID_PREFIX)


def _is_generated_source_untrusted_record(u: dict[str, Any]) -> bool:
    if str(u.get("kind") or "") != "source_untrusted":
        return False
    uid = str(u.get("id") or "")
    return uid.startswith(_GENERATED_SOURCE_UNTRUSTED_ID_PREFIX)


def _reconcile_generated_records(
    pef: PEFState,
    new_uncertainties: list[dict[str, Any]],
) -> None:
    """Drop stale generated records no longer produced this pass.

    Only affects generated records with reserved id prefixes.
    Externally declared uncertainty records are never touched.
    """
    active_ids = {
        str(u.get("id") or "")
        for u in new_uncertainties
        if (
            _is_generated_identity_referent_record(u)
            or _is_generated_stale_record(u)
            or _is_generated_scope_mismatch_record(u)
            or _is_generated_threshold_not_met_record(u)
            or _is_generated_inferential_gap_record(u)
            or _is_generated_source_untrusted_record(u)
        )
    }
    if not pef.open_epistemic_uncertainties:
        return
    pef.open_epistemic_uncertainties = [
        u
        for u in pef.open_epistemic_uncertainties
        if not (
            (
                _is_generated_identity_referent_record(u)
                or _is_generated_stale_record(u)
                or _is_generated_scope_mismatch_record(u)
                or _is_generated_threshold_not_met_record(u)
                or _is_generated_inferential_gap_record(u)
                or _is_generated_source_untrusted_record(u)
            )
            and str(u.get("id") or "") not in active_ids
        )
    ]


def merge_epistemic_uncertainties(
    pef: PEFState,
    new_uncertainties: list[dict[str, Any]],
) -> None:
    """Merge uncertainty records into PEF state without overwriting existing entries.

    Matches by id. A previously resolved entry keeps its status.
    """
    _reconcile_generated_records(pef, new_uncertainties)
    existing_ids: set[str] = {
        str(u.get("id")) for u in pef.open_epistemic_uncertainties
    }
    for u in new_uncertainties:
        uid = str(u.get("id") or "").strip()
        if uid and uid not in existing_ids:
            pef.open_epistemic_uncertainties.append(u)
            existing_ids.add(uid)


# ── PEF uncertainty analysis ───────────────────────────────────────────

def _conflict_description(subject_name: str, relation: str, values: list[str], sources: list[str | None]) -> str:
    named = [s for s in sources if s]
    if named:
        source_clause = " and ".join(named)
        return f"{source_clause} disagree on {subject_name} {relation}."
    vals = " vs. ".join(str(v) for v in values[:3])
    return f"Committed values for {subject_name} {relation} conflict: {vals}."


def _iter_open_unresolved_referent_entries(pef: PEFState) -> list[Any]:
    entries = getattr(pef, "unresolved_referent_registry", None)
    if not isinstance(entries, list):
        return []
    out: list[Any] = []
    for entry in entries:
        if isinstance(entry, dict):
            status = str(entry.get("status") or "").strip()
        else:
            status = str(getattr(entry, "status", "") or "").strip()
        if status == "open":
            out.append(entry)
    return out


def _entry_field(entry: Any, name: str) -> str:
    if hasattr(entry, name):
        return str(getattr(entry, name) or "").strip()
    if isinstance(entry, dict):
        return str(entry.get(name) or "").strip()
    return ""


def _identity_referent_bears_on(entry: Any) -> list[str]:
    blocked_proposition = _entry_field(entry, "blocked_proposition")
    if blocked_proposition:
        return [blocked_proposition]
    head = _entry_field(entry, "head")
    if head:
        return [head]
    span_surface = _entry_field(entry, "span_surface")
    if span_surface:
        return [span_surface]
    token = _entry_field(entry, "token")
    if token:
        return [token]
    entry_id = _entry_field(entry, "entry_id")
    return [entry_id] if entry_id else []


def _identity_referent_description(entry: Any) -> str:
    token = _entry_field(entry, "token") or _entry_field(entry, "span_surface") or "referent"
    blocked = _entry_field(entry, "blocked_proposition")
    if blocked:
        return (
            f"The referent for {token!r} is unresolved in the claim "
            f"{blocked!r}."
        )
    return f"The referent for {token!r} is unresolved."


def _parse_iso_dt(value: str) -> datetime | None:
    s = (value or "").strip()
    if not s:
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _parse_iso_duration(value: str) -> timedelta | None:
    s = (value or "").strip().upper()
    if not s.startswith("P"):
        return None
    days = 0.0
    hours = 0.0
    minutes = 0.0
    cur = ""
    in_time = False
    for ch in s[1:]:
        if ch == "T":
            in_time = True
            continue
        if ch.isdigit() or ch == ".":
            cur += ch
            continue
        if not cur:
            return None
        try:
            num = float(cur)
        except ValueError:
            return None
        cur = ""
        if ch == "D" and not in_time:
            days += num
        elif ch == "H" and in_time:
            hours += num
        elif ch == "M" and in_time:
            minutes += num
        else:
            return None
    if cur:
        return None
    return timedelta(days=days, hours=hours, minutes=minutes)


def _temporal_meta(rel: Any) -> dict[str, Any]:
    rm = rel.relation_metadata if isinstance(rel.relation_metadata, dict) else {}
    tm = rm.get("temporal")
    return tm if isinstance(tm, dict) else {}


def _subject_relation(entity_map: dict[str, str], rel: Any) -> str:
    subject_name = entity_map.get(rel.subject_id, rel.subject_id)
    return f"{subject_name}.{rel.relation}"


def _scope_meta(rel: Any) -> dict[str, Any]:
    rm = rel.relation_metadata if isinstance(rel.relation_metadata, dict) else {}
    sm = rm.get("scope")
    return sm if isinstance(sm, dict) else {}


def _parse_scope_contract(scope_block: dict[str, Any]) -> tuple[dict[str, str], dict[str, str], list[str], str] | None:
    """Parse the four-part scope contract; return None when incomplete or invalid."""
    required = normalize_scope_value_dict(scope_block.get("required_scope"))
    supported_raw = scope_block.get("supported_scope")
    if supported_raw is None:
        supported_raw = scope_block.get("evidence_scope")
    supported = normalize_scope_value_dict(supported_raw)
    if not required or not supported:
        return None

    dimensions = parse_scope_dimensions(scope_block.get("scope_dimensions"))
    if not dimensions:
        return None

    mode = str(scope_block.get("comparison_mode") or "").strip().lower()
    if mode not in SCOPE_COMPARISON_MODES:
        return None

    if not all(str(required.get(d) or "").strip() and str(supported.get(d) or "").strip() for d in dimensions):
        return None

    return required, supported, dimensions, mode


def _scope_mismatch_record_if_any(entity_map: dict[str, str], rel: Any) -> dict[str, Any] | None:
    contract = _parse_scope_contract(_scope_meta(rel))
    if contract is None:
        return None

    required, supported, dimensions, mode = contract
    failed = compare_scope_failure_dimensions(required, supported, dimensions, mode)
    if not failed:
        return None

    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|{mode}|"
        f"{'|'.join(failed)}|{str(rel.object_literal)}"
    )
    meta: dict[str, Any] = {
        "required_scope": required,
        "supported_scope": supported,
        "scope_dimensions": dimensions,
        "comparison_mode": mode,
        "failed_dimensions": failed,
    }
    policy_ref = str(_scope_meta(rel).get("policy_ref") or "").strip()
    if policy_ref:
        meta["policy_ref"] = policy_ref

    return {
        "id": f"{_GENERATED_SCOPE_MISMATCH_ID_PREFIX}{key}",
        "kind": "scope_mismatch",
        "description": (
            "Evidence may be real, current, and trusted, but its supported scope "
            "does not establish the scope required by the proposed claim or action."
        ),
        "bears_on": [_subject_relation(entity_map, rel)],
        "status": "open",
        "meta": meta,
    }


def _threshold_meta(rel: Any) -> dict[str, Any]:
    rm = rel.relation_metadata if isinstance(rel.relation_metadata, dict) else {}
    tm = rm.get("threshold")
    return tm if isinstance(tm, dict) else {}


def _parse_threshold_contract(
    threshold_block: dict[str, Any],
) -> tuple[float, float, str, str, str] | None:
    """Parse the threshold contract; return None when incomplete or invalid."""
    required = normalize_strength_value(threshold_block.get("required_strength"))
    observed = normalize_strength_value(threshold_block.get("observed_strength"))
    if required is None or observed is None:
        return None

    grade = normalize_consequence_grade(threshold_block.get("consequence_grade"))
    if grade is None:
        return None

    threshold_ref = str(threshold_block.get("threshold_ref") or "").strip()
    if not threshold_ref:
        return None

    mode = normalize_threshold_comparison_mode(threshold_block.get("comparison_mode"))
    if mode is None:
        return None

    return required, observed, grade, threshold_ref, mode


def _threshold_not_met_record_if_any(
    entity_map: dict[str, str], rel: Any
) -> dict[str, Any] | None:
    contract = _parse_threshold_contract(_threshold_meta(rel))
    if contract is None:
        return None

    required, observed, grade, threshold_ref, mode = contract
    if not threshold_comparison_fails(observed, required, mode):
        return None

    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|{mode}|"
        f"{grade}|{threshold_ref}|{required}|{observed}|{str(rel.object_literal)}"
    )
    meta: dict[str, Any] = {
        "required_strength": required,
        "observed_strength": observed,
        "consequence_grade": grade,
        "threshold_ref": threshold_ref,
        "comparison_mode": mode,
    }
    policy_ref = str(_threshold_meta(rel).get("policy_ref") or "").strip()
    if policy_ref:
        meta["policy_ref"] = policy_ref

    return {
        "id": f"{_GENERATED_THRESHOLD_NOT_MET_ID_PREFIX}{key}",
        "kind": "threshold_not_met",
        "description": (
            "Applicable evidence exists but does not meet the declared evidential "
            "threshold for this consequence grade."
        ),
        "bears_on": [_subject_relation(entity_map, rel)],
        "status": "open",
        "meta": meta,
    }


def _inference_meta(rel: Any) -> dict[str, Any]:
    rm = rel.relation_metadata if isinstance(rel.relation_metadata, dict) else {}
    im = rm.get("inference")
    return im if isinstance(im, dict) else {}


def _parse_inference_contract(
    inference_block: dict[str, Any],
) -> tuple[list[str], str, str, str, str] | None:
    """Parse the bridge contract; return None when incomplete or invalid."""
    premises_raw = inference_block.get("premises")
    if premises_raw is None:
        premises_raw = inference_block.get("missing_support")
    premises = parse_premises(premises_raw)
    if not premises:
        return None

    conclusion = str(inference_block.get("conclusion") or "").strip()
    if not conclusion:
        return None

    bridge_ref = str(inference_block.get("bridge_ref") or "").strip()
    if not bridge_ref:
        return None

    status = normalize_bridge_status(inference_block.get("bridge_status"))
    if status is None:
        return None

    mode = normalize_inferential_bridge_mode(inference_block.get("bridge_mode"))
    if mode is None:
        return None

    return premises, conclusion, bridge_ref, status, mode


def _inferential_gap_record_if_any(
    entity_map: dict[str, str], rel: Any
) -> dict[str, Any] | None:
    contract = _parse_inference_contract(_inference_meta(rel))
    if contract is None:
        return None

    premises, conclusion, bridge_ref, status, mode = contract
    if mode != INFERENTIAL_BRIDGE_MODE_DEFAULT:
        return None
    if not bridge_status_indicates_gap(status):
        return None

    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|{mode}|"
        f"{status}|{bridge_ref}|{conclusion}|{'|'.join(premises)}"
    )
    meta: dict[str, Any] = {
        "premises": premises,
        "conclusion": conclusion,
        "bridge_ref": bridge_ref,
        "bridge_status": status,
        "bridge_mode": mode,
    }
    policy_ref = str(_inference_meta(rel).get("policy_ref") or "").strip()
    if policy_ref:
        meta["policy_ref"] = policy_ref

    return {
        "id": f"{_GENERATED_INFERENTIAL_GAP_ID_PREFIX}{key}",
        "kind": "inferential_gap",
        "description": (
            "Applicable evidence exists but the declared inference bridge does not "
            "establish the sought conclusion."
        ),
        "bears_on": [conclusion],
        "status": "open",
        "meta": meta,
    }


def _clock_stale_record_if_any(entity_map: dict[str, str], rel: Any) -> dict[str, Any] | None:
    tm = _temporal_meta(rel)
    decay_mode = str(tm.get("decay_mode") or "").strip().lower()
    if decay_mode != "clock":
        return None

    # Mandatory top-level stale contract. Do not infer from other signals.
    if not str(tm.get("timestamp_source") or "").strip():
        return None
    if not str(tm.get("policy_ref") or "").strip():
        return None

    anchor_raw = str(tm.get("observed_at") or tm.get("asserted_at") or "").strip()
    if not anchor_raw:
        return None
    anchor_dt = _parse_iso_dt(anchor_raw)
    if anchor_dt is None:
        return None

    assessed_raw = str(tm.get("assessed_at") or tm.get("decision_time") or "").strip()
    if not assessed_raw:
        return None
    assessed_dt = _parse_iso_dt(assessed_raw)
    if assessed_dt is None:
        return None

    valid_until_raw = str(tm.get("valid_until") or "").strip()
    freshness_raw = str(tm.get("freshness_window") or "").strip()
    if not valid_until_raw and not freshness_raw:
        return None

    stale = False
    if valid_until_raw:
        vu = _parse_iso_dt(valid_until_raw)
        if vu is None:
            return None
        stale = stale or assessed_dt > vu
    if freshness_raw:
        td = _parse_iso_duration(freshness_raw)
        if td is None:
            return None
        stale = stale or (assessed_dt - anchor_dt) > td
    if not stale:
        return None

    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|"
        f"{str(rel.object_literal)}|clock|{anchor_raw}|{assessed_raw}"
    )
    return {
        "id": f"{_GENERATED_STALE_EVIDENCE_ID_PREFIX}{key}",
        "kind": "stale_evidence",
        "description": (
            "Committed evidence is stale under declared clock-decay semantics."
        ),
        "bears_on": [_subject_relation(entity_map, rel)],
        "status": "open",
    }


def _event_stale_record_if_any(
    entity_map: dict[str, str], rel: Any, relationships: list[Any]
) -> dict[str, Any] | None:
    tm = _temporal_meta(rel)
    decay_mode = str(tm.get("decay_mode") or "").strip().lower()
    if decay_mode != "event":
        return None

    # Mandatory top-level stale contract. Do not infer from other signals.
    if not str(tm.get("timestamp_source") or "").strip():
        return None
    if not str(tm.get("policy_ref") or "").strip():
        return None

    anchor_ref = str(tm.get("evidence_ref") or tm.get("claim_key") or "").strip()
    if not anchor_ref:
        return None
    if not str(tm.get("supersession_rule") or tm.get("policy_ref") or "").strip():
        return None

    stale = False
    for cand in relationships:
        cand_tm = _temporal_meta(cand)
        supersedes_ref = str(cand_tm.get("supersedes_ref") or "").strip()
        committed_at = str(cand_tm.get("committed_at") or "").strip()
        if supersedes_ref != anchor_ref:
            continue
        if not committed_at:
            continue
        if _parse_iso_dt(committed_at) is None:
            continue
        if cand.source_turn > rel.source_turn:
            stale = True
            break
    if not stale:
        return None

    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|"
        f"{str(rel.object_literal)}|event|{anchor_ref}"
    )
    return {
        "id": f"{_GENERATED_STALE_EVIDENCE_ID_PREFIX}{key}",
        "kind": "stale_evidence",
        "description": (
            "Committed evidence is stale under declared event-decay semantics "
            "because a superseding event is committed."
        ),
        "bears_on": [_subject_relation(entity_map, rel)],
        "status": "open",
    }


def _source_untrusted_record_if_any(
    entity_map: dict[str, str],
    rel: Any,
    trust_registry: TrustRegistry | None,
) -> dict[str, Any] | None:
    """Generate source_untrusted only under Track C trust contract + registry evaluation."""
    contract = parse_trust_contract(rel)
    if contract is None:
        return None
    if trust_registry is None:
        return None

    evaluation = trust_registry.evaluate_source(
        contract.source_id,
        task_domain=contract.task_domain,
        consequence_grade=contract.consequence_grade,
        trust_registry_ref=contract.trust_registry_ref,
    )
    if not evaluation.registry_evaluated:
        return None
    if evaluation.admissible:
        return None

    bears_on = contract.bears_on or _subject_relation(entity_map, rel)
    key = (
        f"{rel.subject_id}|{rel.relation}|{rel.source_turn}|"
        f"{contract.source_id}|{evaluation.reason}|{str(rel.object_literal)}"
    )
    meta: dict[str, Any] = {
        "source_id": contract.source_id,
        "trust_registry_ref": contract.trust_registry_ref,
        "trust_decision": evaluation.trust_decision or "deny",
        "task_domain": contract.task_domain,
        "consequence_grade": contract.consequence_grade,
        "trust_evaluation_required": True,
    }
    if evaluation.reason:
        meta["trust_basis"] = evaluation.reason
    if contract.policy_ref:
        meta["policy_ref"] = contract.policy_ref
    if contract.authority_map_ref:
        meta["authority_map_ref"] = contract.authority_map_ref
    profile = trust_registry.get_profile(contract.source_id)
    if profile is not None:
        meta["source_class"] = profile.source_class

    return {
        "id": f"{_GENERATED_SOURCE_UNTRUSTED_ID_PREFIX}{key}",
        "kind": "source_untrusted",
        "description": (
            "Committed evidence source does not satisfy declared trust and "
            "authority requirements for this decision class."
        ),
        "bears_on": [bears_on],
        "status": "open",
        "meta": meta,
    }


def pef_uncertainty_analysis(
    pef: PEFState,
    *,
    trust_registry: TrustRegistry | None = None,
) -> list[dict[str, Any]]:
    """Analyse committed PEF state and return epistemic uncertainty records.

    Returns records in open_epistemic_uncertainties dict format
    (id, kind, description, bears_on, status).

    This is deterministic: no adapter, no LLM, no text re-reading.
    """
    records: list[dict[str, Any]] = []

    # ── 1. Conflicting committed claims ────────────────────────────────
    # Group non-negated, non-retracted relationships by (subject_id, relation).
    # Multiple incompatible values for the same predicate = conflicting_models.
    entity_map: dict[str, str] = {e.id: e.name for e in pef.entities.values()}

    groups: dict[tuple[str, str], list] = defaultdict(list)
    for rel in pef.relationships:
        if rel.negated:
            continue
        if rel.claim_status in ("retracted",):
            continue
        key = (rel.subject_id, rel.relation)
        groups[key].append(rel)

    for (subject_id, relation), rels in groups.items():
        if len(rels) < 2:
            continue
        # Collect distinct values
        values: list[Any] = []
        seen_values: list[str] = []
        for r in rels:
            val = r.object_literal if r.object_literal is not None else r.object_entity_id
            val_str = str(val)
            if val_str not in seen_values:
                seen_values.append(val_str)
                values.append(val)
        if len(values) < 2:
            continue  # All rels agree — not a conflict
        subject_name = entity_map.get(subject_id, subject_id)
        sources = [r.source_name for r in rels]
        uid = f"conflict_{subject_id[:8]}_{relation}"
        records.append({
            "id": uid,
            "kind": "conflicting_models",
            "description": _conflict_description(subject_name, relation, [str(v) for v in values], sources),
            "bears_on": [f"{subject_name}.{relation}"],
            "status": "open",
        })

    # ── 2. Unresolved entities ─────────────────────────────────────────
    # Entities committed with resolved=False: current status unknown.
    for entity in pef.entities.values():
        if not entity.resolved:
            uid = f"unresolved_{entity.id[:8]}"
            records.append({
                "id": uid,
                "kind": "unconfirmed_status",
                "description": f"The current status of {entity.name!r} is unresolved.",
                "bears_on": [entity.name],
                "status": "open",
            })

    # ── 3. Blocked retrieval ───────────────────────────────────────────
    # retrieval_unresolved: incompatible facts in retrieved batch not admitted.
    for i, item in enumerate(pef.retrieval_unresolved):
        uid = item.get("id") or f"retrieval_blocked_{i}"
        subject = item.get("subject", "unknown subject")
        relation = item.get("relation", "")
        desc = item.get("description") or (
            f"Retrieved evidence for {subject} {relation} could not be admitted due to conflicts."
        )
        records.append({
            "id": str(uid),
            "kind": "blocked_access",
            "description": desc,
            "bears_on": [f"{subject}.{relation}"] if relation else [subject],
            "status": "open",
        })

    # ── 4. Pending claims ─────────────────────────────────────────────
    # Relationships with claim_status="pending" indicate missing or unresolved observations.
    for rel in pef.relationships:
        if rel.claim_status != "pending":
            continue
        subject_name = entity_map.get(rel.subject_id, rel.subject_id)
        uid = f"pending_{rel.subject_id[:8]}_{rel.relation}"
        records.append({
            "id": uid,
            "kind": "missing_observation",
            "description": f"Expected observation for {subject_name} {rel.relation} is pending or absent.",
            "bears_on": [f"{subject_name}.{rel.relation}"],
            "status": "open",
        })

    # ── 5. Stale evidence generation (strict declared decay semantics) ─
    for rel in pef.relationships:
        tm = _temporal_meta(rel)
        decay_mode = str(tm.get("decay_mode") or "").strip().lower()
        if decay_mode not in {"clock", "event"}:
            continue
        stale_rec = (
            _clock_stale_record_if_any(entity_map, rel)
            if decay_mode == "clock"
            else _event_stale_record_if_any(entity_map, rel, pef.relationships)
        )
        if stale_rec is not None:
            records.append(stale_rec)

    # ── 6. Scope mismatch generation (explicit four-part scope contract) ─
    for rel in pef.relationships:
        scope_rec = _scope_mismatch_record_if_any(entity_map, rel)
        if scope_rec is not None:
            records.append(scope_rec)

    # ── 7. Threshold not met generation (explicit threshold contract) ─
    for rel in pef.relationships:
        threshold_rec = _threshold_not_met_record_if_any(entity_map, rel)
        if threshold_rec is not None:
            records.append(threshold_rec)

    # ── 8. Inferential gap generation (explicit bridge contract) ──────
    for rel in pef.relationships:
        inferential_rec = _inferential_gap_record_if_any(entity_map, rel)
        if inferential_rec is not None:
            records.append(inferential_rec)

    # ── 9. Source untrusted generation (Track C trust contract + registry) ─
    for rel in pef.relationships:
        untrusted_rec = _source_untrusted_record_if_any(entity_map, rel, trust_registry)
        if untrusted_rec is not None:
            records.append(untrusted_rec)

    # ── 10. Unresolved referent registry ──────────────────────────────
    # Deterministic Phase 3A generation for unresolved referent constraints.
    for entry in _iter_open_unresolved_referent_entries(pef):
        entry_id = _entry_field(entry, "entry_id")
        if not entry_id:
            token = _entry_field(entry, "token") or "referent"
            introduced_turn = _entry_field(entry, "introduced_turn") or "0"
            entry_id = f"{token}@{introduced_turn}"
        records.append({
            "id": f"{_GENERATED_IDENTITY_REFERENT_UNRESOLVED_ID_PREFIX}{entry_id}",
            "kind": "identity_or_referent_unresolved",
            "description": _identity_referent_description(entry),
            "bears_on": _identity_referent_bears_on(entry),
            "status": "open",
        })

    return records
